### ISSUE TITLE
[compile error] No maven dependency storm 0.9.1-lorenz-SNAPSHOT

### ISSUE THREAD

**Issue by healthyjk** [lorenzfischer/storm-scheduler#1]
Hello lorenzfischer, 

I'm interested in your storm scheduler. When I build it, I found I cannot download the dependency of storm with version 0.9.1-lorenz-SNAPSHOT. And I think it is a custom version that you extend the offical storm. 

Could you give me a storm jar file so that I can compile it successfully?

Thank you so much!

**Comment by lorenzfischer** [comment]
Hi

It has been a while since I last compiled this and I don't have the exact version, anymore. But, if I remember correctly, I only put some debugging code into Storm that is not actually necessary to run it. Have you tried running it with 0.9.1?

Cheers,
Lorenz

**Comment by healthyjk** [comment]
Hi lorenzfischer, 

I'm very glad to receive your reply. I follow your advice and change 0.9.1-lorenz-SNAPSHOT to 0.9.1-incubating. And I successfully compile the stools-core module. Thank you.
Next I need to build the adaptive scheduler by aniello you compared to so that I can build your stools-topo module. 
Anyway, thank you very much!

Cherrs, 
Healthyjk

**Comment by healthyjk** [comment]
Hi lorenzfischer,

I have compiled the code successfully. Thanks great for your help and share. Good luck!

Cherrs, 
Healthyjk
